// เราจะใช้คำสั่ง `npx prisma db seed` เพื่อรันไฟล์นี้

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {

  // ---------- BUILDING ----------
  await prisma.building.createMany({
    data: [
      { buildingCode: "A", buildingName: "อาคารบริหาร" },
      { buildingCode: "AE", buildingName: "อาคารปฏิบัติการวิศวกรรมเกษตร" },
      { buildingCode: "B", buildingName: "อาคารเฉลิมพระเกียรติ 6 รอบพระชนพรรษา" },
      { buildingCode: "C", buildingName: "อาคารปฏิบัติการวิทยาศาสตร์" },
      { buildingCode: "D", buildingName: "อาคารปฏิบัติการวิศวกรรมศาสตร์" },
      { buildingCode: "DORM", buildingName: "หอพักนักศึกษา วิทยาเขตชุมพรเขตรอุดมศักดิ์" },
      { buildingCode: "E", buildingName: "อาคารสำนักวิชาพื้นฐาานทั่วไป" },
      { buildingCode: "EE", buildingName: "อาคารปฏิบัติการอิเล็กทรอนิกส์" },
      { buildingCode: "FS1", buildingName: "อาคารปฎิบัติการวิทยาศาสตร์การประมง" },
      { buildingCode: "FS2", buildingName: "อาคารปฎิบัติการเพาะเลี้ยงสัตว์น้ำ" },
      { buildingCode: "HO", buildingName: "อาคารปฏิบัติการพืชสวน" },
      { buildingCode: "KMITLPCC", buildingName: "พื้นที่บริเวณ วิทยาเขตชุมพรเขตรอุดมศักดิ์" },
      { buildingCode: "ME", buildingName: "อาคารปฏิบัติการเครื่องกล" },
      { buildingCode: "STADIUM", buildingName: "สถานที่ออกกำลังกาย และสนามกีฬา" }
    ]
  });

  // ---------- ROOM ----------
  await prisma.room.createMany({
    data: [
      { roomCode: "A304", buildingCode: "A", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "A309", buildingCode: "A", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "AE", buildingCode: "AE", roomFloor: "", roomCapacity: "", roomDesc: "อาคารปฎิบัติการวิศวกรรมเกษตร" },

      { roomCode: "B105", buildingCode: "B", roomFloor: "1", roomCapacity: "25", roomDesc: "ห้องปฏิบัติการวิทยาศาสตร์เนื้อสัตว์" },
      { roomCode: "B106", buildingCode: "B", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้องปฏิบัติการเทคโนโลยีชีวภาพ" },
      { roomCode: "B107", buildingCode: "B", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้องปฏิบัติการวิทยาศาสตร์การประมง" },
      { roomCode: "B108", buildingCode: "B", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้องปฏิบัติการสรีรวิทยาของสัตว์และกายวิภาคสัตว์" },
      { roomCode: "B109", buildingCode: "B", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้อง Smart cassroom" },
      { roomCode: "B110", buildingCode: "B", roomFloor: "1", roomCapacity: "25", roomDesc: "ห้องปฎิบัติการแปรรูปอาหาร" },
      { roomCode: "B113", buildingCode: "B", roomFloor: "1", roomCapacity: "25", roomDesc: "ห้องปฎิบัติการแปรรูปน้ำนม" },
      { roomCode: "B114", buildingCode: "B", roomFloor: "1", roomCapacity: "25", roomDesc: "ห้องปฎิบัติการแปรรูปพืช" },

      { roomCode: "B206", buildingCode: "B", roomFloor: "2", roomCapacity: "25", roomDesc: "ห้องปฎิบัติการโภชนศาสตร์สัตว์" },
      { roomCode: "B207", buildingCode: "B", roomFloor: "2", roomCapacity: "25", roomDesc: "ห้องปฎิบัติการเคมี" },
      { roomCode: "B208", buildingCode: "B", roomFloor: "2", roomCapacity: "35", roomDesc: "ห้องปฎิบัติการเคมี" },
      { roomCode: "B209", buildingCode: "B", roomFloor: "2", roomCapacity: "35", roomDesc: "ห้องปฎิบัติการโภชนศาสตร์สัตว์" },

      { roomCode: "B212", buildingCode: "B", roomFloor: "2", roomCapacity: "120", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B213", buildingCode: "B", roomFloor: "2", roomCapacity: "120", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B214", buildingCode: "B", roomFloor: "2", roomCapacity: "120", roomDesc: "ห้องเรียนบรรยาย" },

      { roomCode: "B217", buildingCode: "B", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องปฎิบัติการภาษา" },
      { roomCode: "B218", buildingCode: "B", roomFloor: "2", roomCapacity: "40", roomDesc: "ห้องปฎิบัติการคอมพิวเตอร์" },
      { roomCode: "B219", buildingCode: "B", roomFloor: "2", roomCapacity: "40", roomDesc: "ห้องปฎิบัติการคอมพิวเตอร์" },

      { roomCode: "B301", buildingCode: "B", roomFloor: "3", roomCapacity: "500", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B304", buildingCode: "B", roomFloor: "3", roomCapacity: "70", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B305", buildingCode: "B", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องปฎิบัติการชีววิทยา" },
      { roomCode: "B306", buildingCode: "B", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องปฎิบัติการพืช" },

      { roomCode: "B308", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B309", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B310", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B311", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B312", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B313", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },

      { roomCode: "B315", buildingCode: "B", roomFloor: "3", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B316", buildingCode: "B", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องปฎบัติการวิศวกรรมสารสนเทศ" },
      { roomCode: "B317", buildingCode: "B", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องปฎบัติการวิศวกรรมสารสนเทศ" },
      { roomCode: "B318", buildingCode: "B", roomFloor: "3", roomCapacity: "120", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "B319", buildingCode: "B", roomFloor: "3", roomCapacity: "120", roomDesc: "ห้องเรียนบรรยาย" },

      { roomCode: "BA201", buildingCode: "E", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA202", buildingCode: "E", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA203", buildingCode: "E", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA204", buildingCode: "E", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA205", buildingCode: "E", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA206", buildingCode: "E", roomFloor: "2", roomCapacity: "50", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA207", buildingCode: "E", roomFloor: "2", roomCapacity: "70", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "BA208", buildingCode: "E", roomFloor: "2", roomCapacity: "40", roomDesc: "ห้อง Smart cassroom" },

      { roomCode: "C104", buildingCode: "C", roomFloor: "1", roomCapacity: "35", roomDesc: "ห้องปฎิติบัติการฟิสิกส์" },
      { roomCode: "C113", buildingCode: "C", roomFloor: "1", roomCapacity: "35", roomDesc: "ห้องปฎิติบัติการฟิสิกส์" },
      { roomCode: "C204", buildingCode: "C", roomFloor: "2", roomCapacity: "35", roomDesc: "ห้องปฎิติบัติการฟิสิกส์" },
      { roomCode: "C205", buildingCode: "C", roomFloor: "2", roomCapacity: "35", roomDesc: "ห้องปฎิบัติการเคมี" },

      { roomCode: "D203", buildingCode: "D", roomFloor: "2", roomCapacity: "40", roomDesc: "ห้องปฎิบัติการวิศวกรรมพลังงาน" },
      { roomCode: "D208", buildingCode: "D", roomFloor: "2", roomCapacity: "70", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "D312", buildingCode: "D", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องปฎบัติการวิศวกรรมสารสนเทศ" },
      { roomCode: "D313", buildingCode: "D", roomFloor: "3", roomCapacity: "30", roomDesc: "ห้องปฎบัติการวิศวกรรมสารสนเทศ" },
      { roomCode: "D406", buildingCode: "D", roomFloor: "4", roomCapacity: "250", roomDesc: "ห้องเรียนบรรยาย" },

      { roomCode: "DORM-A", buildingCode: "DORM", roomFloor: "", roomCapacity: "", roomDesc: "อาคารหอพักนักศึกษา ตึก A" },
      { roomCode: "DORM-B", buildingCode: "DORM", roomFloor: "", roomCapacity: "", roomDesc: "อาคารหอพักนักศึกษา ตึก B" },
      { roomCode: "DORM-C", buildingCode: "DORM", roomFloor: "", roomCapacity: "", roomDesc: "อาคารหอพักนักศึกษา ตึก C" },
      { roomCode: "DORM-GR", buildingCode: "DORM", roomFloor: "", roomCapacity: "", roomDesc: "บริเวณพื่นที่หอพักนักศึกษา" },

      { roomCode: "E107", buildingCode: "E", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้องปฎิบัติการวิศวกรรมสารสนเทศ" },
      { roomCode: "E109", buildingCode: "E", roomFloor: "1", roomCapacity: "25", roomDesc: "ห้องเขียนแบบ" },
      { roomCode: "E110", buildingCode: "E", roomFloor: "1", roomCapacity: "25", roomDesc: "ห้องเขียนแบบ" },
      { roomCode: "E111", buildingCode: "E", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้องปฎิบัติการวิศวกรรมสารสนเทศ" },
      { roomCode: "E113", buildingCode: "E", roomFloor: "1", roomCapacity: "30", roomDesc: "ห้องปฎิบัติการวิศวกรรมสารสนเทศ" },

      { roomCode: "E301", buildingCode: "E", roomFloor: "3", roomCapacity: "200", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "E303", buildingCode: "E", roomFloor: "3", roomCapacity: "70", roomDesc: "ห้องเรียนบรรยาย" },
      { roomCode: "E304", buildingCode: "E", roomFloor: "3", roomCapacity: "200", roomDesc: "ห้องเรียนบรรยาย" },

      { roomCode: "EE", buildingCode: "EE", roomFloor: "", roomCapacity: "", roomDesc: "อาคารปฎิบัติการอิเล็กทรอนิกส์" },
      { roomCode: "FS1", buildingCode: "FS1", roomFloor: "", roomCapacity: "", roomDesc: "อาคารปฎิบัติการวิทยาศาสตร์การประมง" },
      { roomCode: "FS2", buildingCode: "FS2", roomFloor: "", roomCapacity: "", roomDesc: "อาคารปฎิบัติการเพราะเลี้ยงสัตว์น้ำ" },
      { roomCode: "HO", buildingCode: "HO", roomFloor: "", roomCapacity: "", roomDesc: "อาคารปฎิบัติการพืชสวน" },

      { roomCode: "K-CANTEEN", buildingCode: "KMITLPCC", roomFloor: "1", roomCapacity: "", roomDesc: "โรงอาหาร" },
      { roomCode: "K-FARM", buildingCode: "KMITLPCC", roomFloor: "1", roomCapacity: "", roomDesc: "ฟาร์มเกษตร" },
      { roomCode: "K-SECURITY", buildingCode: "KMITLPCC", roomFloor: "1", roomCapacity: "", roomDesc: "จุดเช็คอิน รปภ." },
      { roomCode: "K-SHOP", buildingCode: "KMITLPCC", roomFloor: "1", roomCapacity: "", roomDesc: "ร้านค้าภายใน" },
      { roomCode: "K-SWEEP", buildingCode: "KMITLPCC", roomFloor: "1", roomCapacity: "", roomDesc: "จุดเช็คอิน แม่บ้าน" },

      { roomCode: "LIB", buildingCode: "B", roomFloor: "2", roomCapacity: "", roomDesc: "ห้องสมุด วิทยาเขตชุมพรเขตรอุดมศักดิ์" },
      { roomCode: "ME", buildingCode: "ME", roomFloor: "", roomCapacity: "", roomDesc: "อาคารปฎิบัติการเครื่องกล" },
      { roomCode: "YIM1", buildingCode: "STADIUM", roomFloor: "", roomCapacity: "", roomDesc: "อาคารยิมเนเซียม" }
    ],
    skipDuplicates: true
  });
  // ---------- ROLE ----------
  await prisma.role.createMany({
    data: [
      {
        roleId: "admin",
        name: "Administrator"
      },
      {
        roleId: "teacher",
        name: "Teacher"
      },
      {
        roleId: "student",
        name: "Student"
      }
    ],
    skipDuplicates: true
  });


  // ---------- MAJOR ----------
  await prisma.major.createMany({
    data: [
      {
        majorId: "CE", name: "Computer Engineering"
      },

    ],
    skipDuplicates: true
  });


  // ---------- USER (ADMIN) ----------
  await prisma.user.create({
    data: {
      StudentId: "admin001",
      prefix: "",
      fname: "System",
      lname: "Admin",
      nickname: "admin",
      email: "admin@system.com",
      phone: "",
      gen: "",
      majorId: "CE",
      roleId: "admin"
    }
  });


  // ---------- STUDENTS ----------
  await prisma.user.createMany({
    data: [
      { StudentId: "64200001", prefix: "นาย", fname: "สมชาย", lname: "ใจดี", nickname: "ชาย", email: "64200001@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200002", prefix: "นาย", fname: "กฎทบวง", lname: "เณรวงษ์", nickname: "เมน", email: "64200002@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200030", prefix: "นาย", fname: "จีรวัฒน์", lname: "ศรีบุรินทร์", nickname: "อั้น", email: "64200030@kmitl.ac.th", phone: "0983318289", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200035", prefix: "นางสาว", fname: "ชณิดาภรณ์", lname: "หนูรักษ์", nickname: "", email: "64200035@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200039", prefix: "นาย", fname: "ชยากุล", lname: "ธรรมสวาสดิ์", nickname: "", email: "64200039@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200042", prefix: "นาย", fname: "ชัชวาลย์", lname: "ขวัญเมือง", nickname: "เบสท์", email: "64200042@kmitl.ac.th", phone: "0971363171", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200055", prefix: "นาย", fname: "ณัฏฐ์", lname: "แจ้งจิตร", nickname: "", email: "64200055@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200058", prefix: "นาย", fname: "ณัฐนันท์", lname: "กัญจนกาญจน์", nickname: "", email: "64200058@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200061", prefix: "นาย", fname: "ณัฐพงศ์", lname: "สิงห์เขา", nickname: "", email: "64200061@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200063", prefix: "นาย", fname: "ณัฐภัทร", lname: "เขียวอุดม", nickname: "", email: "64200063@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200081", prefix: "นาย", fname: "ธนรัฐ", lname: "ปัจฉิมบุตร", nickname: "พาย", email: "64200081@kmitl.ac.th", phone: "0622139891", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200087", prefix: "นาย", fname: "ธนาวุธ", lname: "เจริญผล", nickname: "", email: "64200087@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200094", prefix: "นางสาว", fname: "ธิติสุดา", lname: "วงศ์วิเศษศักดิ์", nickname: "อ้อเเอ้", email: "64200094@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200106", prefix: "นาย", fname: "นราวิชญ์", lname: "ชูช่วย", nickname: "ทาม", email: "64200106@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200112", prefix: "นางสาว", fname: "นัชนันท์", lname: "งามพริ้ง", nickname: "", email: "64200112@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200123", prefix: "นาย", fname: "บวรลักษณ์", lname: "ศิลป์สกุลเจริญ", nickname: "บวร", email: "64200123@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200129", prefix: "นาย", fname: "ปรัชญ์สพล", lname: "ยอดดำเนิน", nickname: "", email: "64200129@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200130", prefix: "นาย", fname: "ปรัชญา", lname: "ใจห้าว", nickname: "", email: "64200130@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200135", prefix: "นางสาว", fname: "ปาริฉัตร", lname: "ชุมจันทร์", nickname: "", email: "64200135@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200137", prefix: "นาย", fname: "ปุญญพัฒน์", lname: "สุวรรณสิทธิ์", nickname: "", email: "64200137@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200146", prefix: "นาย", fname: "พรหมพริษฐ์", lname: "พรหมรักษ์", nickname: "", email: "64200146@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200152", prefix: "นาย", fname: "พสิษฐ์", lname: "กิจเจริญ", nickname: "", email: "64200152@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200160", prefix: "นาย", fname: "พีระพล", lname: "เอียดเลื่อน", nickname: "", email: "64200160@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200185", prefix: "นางสาว", fname: "เมขลา", lname: "สุดเหลือ", nickname: "ไอซ์", email: "64200185@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200191", prefix: "นางสาว", fname: "รวิสรา", lname: "ขยายแย้ม", nickname: "มิวสิค", email: "64200191@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200192", prefix: "นาย", fname: "รัชชานนท์", lname: "รัชตะวรรณ", nickname: "", email: "64200192@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200193", prefix: "นางสาว", fname: "รัญชิดา", lname: "เนตรอนงค์", nickname: "", email: "64200193@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200203", prefix: "นาย", fname: "เลิศวุฒิ", lname: "จิรรัชวณิช", nickname: "ไกด์", email: "64200203@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200220", prefix: "นาย", fname: "วุฒิภัทร", lname: "อึ๊งเหมอนันต์", nickname: "", email: "64200220@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200222", prefix: "นางสาว", fname: "ศรัณญา", lname: "ศรีกัน", nickname: "", email: "64200222@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200226", prefix: "นาย", fname: "ศศิพงศ์", lname: "จิตต์เอื้อเฟื้อ", nickname: "เบียร์", email: "64200226@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200230", prefix: "นาย", fname: "ศิวกร", lname: "ไชยฤทธิ์", nickname: "", email: "64200230@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200232", prefix: "นางสาว", fname: "ศุจีภรณ์", lname: "วรรณโร", nickname: "", email: "64200232@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200247", prefix: "นาย", fname: "สุทธิกานต์", lname: "ศรีเพชร", nickname: "", email: "64200247@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200255", prefix: "นาย", fname: "เสฎฐวุฒิ", lname: "กสิวุฒิเชิดชูชัย", nickname: "บิ๊ก", email: "64200255@kmitl.ac.th", phone: "0822957983", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200258", prefix: "นาย", fname: "อติวิชญ์", lname: "ฐานะวัฒนา", nickname: "", email: "64200258@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200273", prefix: "นาย", fname: "อรัญชัย", lname: "แก้วเลื่อน", nickname: "", email: "64200273@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200284", prefix: "นาย", fname: "อิทธิภัทร์", lname: "เพิงรัตน์", nickname: "", email: "64200284@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200289", prefix: "นาย", fname: "กฤษณ์", lname: "คงคา", nickname: "เอิร์ธ", email: "64200289@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200290", prefix: "นางสาว", fname: "กัญญาวีร์", lname: "ครึ่งธิ", nickname: "เเคท", email: "64200290@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200312", prefix: "นาย", fname: "ธณชนน์", lname: "เครือเหลา", nickname: "", email: "64200312@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200343", prefix: "นาย", fname: "ภวพรรธน์", lname: "กิตติเจริญลัคน์", nickname: "", email: "64200343@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200346", prefix: "นาย", fname: "ภาสกร", lname: "สุวรรณมณี", nickname: "กอล์ฟ", email: "64200346@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200358", prefix: "นาย", fname: "วารินทร์", lname: "พรหมพิชัย", nickname: "", email: "64200358@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200369", prefix: "นางสาว", fname: "อรสินี", lname: "เกตุเพ็ชร", nickname: "เเอมป์", email: "64200369@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200374", prefix: "นาย", fname: "อัสนีย์", lname: "แซ่เฮียบ", nickname: "", email: "64200374@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "64200377", prefix: "นางสาว", fname: "อิสราภรณ์", lname: "ทองปานดี", nickname: "วิว", email: "64200377@kmitl.ac.th", phone: "", gen: "CE01", majorId: "CE", roleId: "student" },
      { StudentId: "65200006", prefix: "นางสาว", fname: "กรกนก", lname: "สัทธาพงษ์", nickname: "เมย์", email: "65200006@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200009", prefix: "นาย", fname: "กรณ์ดนัย", lname: "ทิพย์จำนงค์", nickname: "นาย", email: "65200009@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200010", prefix: "นางสาว", fname: "กรรณิการ์", lname: "พุ่มสนธิ์", nickname: "กันต์", email: "65200010@kmitl.ac.th", phone: "0925971248", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200013", prefix: "นางสาว", fname: "กฤตยกรรณ", lname: "สีแตงสุก", nickname: "", email: "65200013@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200015", prefix: "นาย", fname: "กฤษฎา", lname: "พุทธะสุภะ", nickname: "สปาย", email: "65200015@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200020", prefix: "นางสาว", fname: "กวิสรา", lname: "แซ่เซี้ย", nickname: "แตงโม", email: "65200020@kmitl.ac.th", phone: "0621828445", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200027", prefix: "นาย", fname: "กันตพล", lname: "ศรีจันทร์", nickname: "ตูน", email: "65200027@kmitl.ac.th", phone: "0955373055", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200033", prefix: "นาย", fname: "กิตติภณ", lname: "เฟื่องศิลา", nickname: "เชพ", email: "65200033@kmitl.ac.th", phone: "0123456789", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200035", prefix: "นาย", fname: "กิติพงษ์", lname: "ไชยมิตร", nickname: "เบนซ์", email: "65200035@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200037", prefix: "นาย", fname: "กีรกิตติกร", lname: "สมแก้ว", nickname: "นนท์", email: "65200037@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200039", prefix: "นาย", fname: "โกฎล", lname: "วสุลิปิกร", nickname: "ไตเติ้ล", email: "65200039@kmitl.ac.th", phone: "0963082044", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200046", prefix: "นาย", fname: "คุณานนต์", lname: "ขาวขำ", nickname: "ไบรท์", email: "65200046@kmitl.ac.th", phone: "0638816647", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200048", prefix: "นาย", fname: "จักรพรรดิ์", lname: "ใสสุชล", nickname: "ยีนส์", email: "65200048@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200056", prefix: "นางสาว", fname: "จิรานุช", lname: "จันทร์น้อย", nickname: "ลูกน้ำ", email: "65200056@kmitl.ac.th", phone: "0928994117", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200066", prefix: "นาย", fname: "เจมส์", lname: "ตุลยนิษก์", nickname: "เจมส์", email: "65200066@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200078", prefix: "นาย", fname: "ชนินทร์ภัทร", lname: "ทองรักษ์", nickname: "โดนัท", email: "65200078@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200079", prefix: "นาย", fname: "ชโยดม", lname: "เปี่ยมไทย", nickname: "เอซ", email: "65200079@kmitl.ac.th", phone: "0947974649", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200084", prefix: "นาย", fname: "ชลทิศ", lname: "สถิตชัย", nickname: "เอเป็ก", email: "65200084@kmitl.ac.th", phone: "0926050868", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200089", prefix: "นาย", fname: "ชาญชัย", lname: "บุญนำ", nickname: "", email: "65200089@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200093", prefix: "นางสาว", fname: "ชุติมา", lname: "วงศ์สวัสดิ์", nickname: "เบม", email: "65200093@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200095", prefix: "นาย", fname: "ไชยธีร์", lname: "สุบการี", nickname: "อาร์ท", email: "65200095@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200097", prefix: "นาย", fname: "นายญาณาธิป", lname: "อินพฤกษา", nickname: "พีช", email: "65200097@kmitl.ac.th", phone: "0897858719", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200099", prefix: "นาย", fname: "ฐาปกรณ์", lname: "โพธิขาว", nickname: "กร", email: "65200099@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200100", prefix: "นาย", fname: "ฐิติกมล", lname: "สวนแยง", nickname: "เเทน", email: "65200100@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200103", prefix: "นาย", fname: "ณกาญจน์", lname: "อยู่ประเสริฐ", nickname: "ปราชญ์", email: "65200103@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200113", prefix: "นาย", fname: "ณัฏฐกิตติ์", lname: "บัวจันทร์", nickname: "ซิม", email: "65200113@kmitl.ac.th", phone: "0887844998", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200119", prefix: "นาย", fname: "ณัฐกุล", lname: "เอกเอี่ยม", nickname: "เป๊ก", email: "65200119@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200122", prefix: "นางสาว", fname: "ณัฐวรา", lname: "นาคงาม", nickname: "ครีม", email: "65200122@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200128", prefix: "นางสาว", fname: "ดนุนุช", lname: "เกตุทองหลาง", nickname: "ไข่มุก", email: "65200128@kmitl.ac.th", phone: "0947878189", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200129", prefix: "นาย", fname: "ดลนที", lname: "ประเดิมรัตนกุล", nickname: "โดม", email: "65200129@kmitl.ac.th", phone: "0851544151", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200133", prefix: "นาย", fname: "ต่อตระกูล", lname: "แซ่เล้า", nickname: "ต่อ", email: "65200133@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200134", prefix: "นาย", fname: "ติณณภพ", lname: "พรมคำ", nickname: "กีตาร์", email: "65200134@kmitl.ac.th", phone: "0651140096", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200135", prefix: "นาย", fname: "ตุลยวัต", lname: "ชนูดหอม", nickname: "ต๊ะ", email: "65200135@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200144", prefix: "นาย", fname: "ทีปกร", lname: "แพกุล", nickname: "กัส", email: "65200144@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200150", prefix: "นาย", fname: "ธนพนธ์", lname: "กาญจนรุ่ง", nickname: "เวฟ", email: "65200150@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200154", prefix: "นาย", fname: "ธนภัทร", lname: "วงศ์เศรษฐโชติ", nickname: "ทาม", email: "65200154@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200156", prefix: "นาย", fname: "ธนภัทร", lname: "สุขกรี", nickname: "ไอหัวควย", email: "65200156@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200162", prefix: "นาย", fname: "ธนาดร", lname: "รัชตะปีติ", nickname: "ดอนนี่", email: "65200162@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200164", prefix: "นาย", fname: "ธนาวัฒน์", lname: "สระทองด้วง", nickname: "หมี", email: "65200164@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200169", prefix: "นางสาว", fname: "ธัญญาลักษณ์", lname: "ทองสงค์", nickname: "ทิพย์", email: "65200169@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200171", prefix: "นาย", fname: "ธัญวุฒิ", lname: "ชนะ", nickname: "เจี๊ยบ", email: "65200171@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200177", prefix: "นาย", fname: "ธีร์ธวัช", lname: "ชอุ่มผล", nickname: "มาร์ท", email: "65200177@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200178", prefix: "นาย", fname: "นายธีรภัทร์", lname: "ยอดพยุต", nickname: "เนส", email: "65200178@kmitl.ac.th", phone: "0994141190", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200184", prefix: "นาย", fname: "นันทวุฒิ", lname: "เณรแตง", nickname: "มาย", email: "65200184@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200185", prefix: "นางสาว", fname: "นันท์สินี", lname: "คำลี", nickname: "กาแฟ", email: "65200185@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200197", prefix: "นาย", fname: "เบญจพล", lname: "เม่นแม่สลิด", nickname: "", email: "65200197@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200209", prefix: "นาย", fname: "ปวรปรัชญ์", lname: "จันทร์ต๊ะ", nickname: "", email: "65200209@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200211", prefix: "นาย", fname: "ปัณณทัต", lname: "ลุ่นเซียะ", nickname: "ปิง", email: "65200211@kmitl.ac.th", phone: "00822813140", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200224", prefix: "นาย", fname: "พชรพล", lname: "พรหมเพศ", nickname: "คิม", email: "65200224@kmitl.ac.th", phone: "0828016223", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200241", prefix: "นาย", fname: "พิสิษฐ์", lname: "วีรสถาพร", nickname: "ไชร์", email: "65200241@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200254", prefix: "นาย", fname: "ภาคิม", lname: "สงวนพัฒน์", nickname: "เติร์ก", email: "65200254@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200264", prefix: "นาย", fname: "ภูผา", lname: "บุญพล", nickname: "อ่าวไทย", email: "65200264@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200275", prefix: "นาย", fname: "ภูวิศร", lname: "ทองตะโก", nickname: "ไบค์", email: "65200265@kmitl.ac.th", phone: "0957789986", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200271", prefix: "นาย", fname: "ภูฤทธิ์", lname: "ไชยยางพานิช", nickname: "ภู", email: "65200271@kmitl.ac.th", phone: "0936471399", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200272", prefix: "นางสาว", fname: "ภูวณิดา", lname: "เรืองด้วง", nickname: "กุ๊กกิ๊ก", email: "65200272@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200273", prefix: "นาย", fname: "ภูวดล", lname: "สมบัติมาก", nickname: "เพชรมายา", email: "65200273@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200277", prefix: "นาย", fname: "มูฮัยมิน", lname: "มามะ", nickname: "มิน", email: "65200277@kmitl.ac.th", phone: "0828144748", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200279", prefix: "นาย", fname: "ยงศักดิ์", lname: "แสงสุข", nickname: "นีโอ", email: "65200279@kmitl.ac.th", phone: "0952909471", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200287", prefix: "นาย", fname: "รัตนพล", lname: "สมบูรณ์", nickname: "ที", email: "65200287@kmitl.ac.th", phone: "0836835931", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200294", prefix: "นาย", fname: "วงศกร", lname: "วิโนทัย", nickname: "อั้ม", email: "65200294@kmitl.ac.th", phone: "0886463069", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200305", prefix: "นาย", fname: "วัชภล", lname: "ทับแสง", nickname: "ตี๋", email: "65200305@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200317", prefix: "นาย", fname: "ศิวกร", lname: "ล้อมวงศ์", nickname: "ปลั๊ก", email: "65200317@kmitl.ac.th", phone: "0625137656", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200343", prefix: "นาย", fname: "สุทธิรัตน์", lname: "เหมือนสร้อย", nickname: "เฟิร์ส", email: "65200343@kmitl.ac.th", phone: "0917351023", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200353", prefix: "นาย", fname: "สุภัทรชัย", lname: "", nickname: "ตั้ม", email: "65200353@kmitl.ac.th", phone: "0935835313", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200354", prefix: "นางสาว", fname: "สุภาพร", lname: "ผั่วสกุล", nickname: "เมย์", email: "65200354@kmitl.ac.th", phone: "0980175461", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200356", prefix: "นางสาว", fname: "สุสาคร", lname: "ภมรานนท์", nickname: "สาคร", email: "65200356@kmitl.ac.th", phone: "0936081160", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200358", prefix: "นาย", fname: "เสฏฐวุฒิ", lname: "ไกรนรา", nickname: "ฟลุ๊ค", email: "65200358@kmitl.ac.th", phone: "0929847340", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200359", prefix: "นางสาว", fname: "หนึ่งฤทัย", lname: "แท้สูงเนิน", nickname: "กิ๊ฟ", email: "65200359@kmitl.ac.th", phone: "0837788259", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200365", prefix: "นาย", fname: "อติวิชญ์", lname: "ทองมาอิ่ม", nickname: "ฟอร์ด", email: "65200365@kmitl.ac.th", phone: "0877381919", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200366", prefix: "นาย", fname: "อนิวัตติ์", lname: "ถิ่นนัยธร", nickname: "ก็อต", email: "65200366@kmitl.ac.th", phone: "0980417457", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200368", prefix: "นาย", fname: "อนุวัตร์", lname: "วันจงคำ", nickname: "กาย", email: "65200368@kmitl.ac.th", phone: "0897614902", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200369", prefix: "นางสาว", fname: "อภิญญา", lname: "คนึงหาญ", nickname: "ปรางค์", email: "65200369@kmitl.ac.th", phone: "0617047791", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200373", prefix: "นางสาว", fname: "อริสดา", lname: "มะบารู", nickname: "อัยดา", email: "65200373@kmitl.ac.th", phone: "0864738081", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200380", prefix: "นาย", fname: "อาณัติ", lname: "ศรีจันทร์", nickname: "ไอซ์", email: "65200380@kmitl.ac.th", phone: "0982724669", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200382", prefix: "นาย", fname: "อิทธิพล", lname: "นิจสินธุ์", nickname: "ทิว", email: "65200382@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200383", prefix: "นางสาว", fname: "อินทิรา", lname: "เรืองชาตรี", nickname: "อิน", email: "65200383@kmitl.ac.th", phone: "0937284127", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200385", prefix: "นาย", fname: "อิสระ", lname: "สุขอินทร์", nickname: "บังโต", email: "65200385@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200389", prefix: "นาย", fname: "อุสมาน", lname: "เจ๊ะอาลี", nickname: "49 เจ๊ะเเจ๊ะ", email: "65200389@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200393", prefix: "นาย", fname: "ฮาริช", lname: "ไพรพฤกษ์", nickname: "บัง", email: "65200393@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "66200004", prefix: "นางสาว", fname: "กมลนัทธ์", lname: "รักกิจ", nickname: "แนน", email: "66200004@kmitl.ac.th", phone: "0634760597", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200009", prefix: "นางสาว", fname: "กรรณธิชา", lname: "สงเสริฐ", nickname: "", email: "66200009@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200011", prefix: "นาย", fname: "กฤตพัฒน์", lname: "ยืดยาว", nickname: "กาโด้", email: "66200011@kmitl.ac.th", phone: "0918206741", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200012", prefix: "นาย", fname: "กฤตภาส", lname: "เพ่งผุดผ่อง", nickname: "อัส", email: "66200012@kmitl.ac.th", phone: "0902537787", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200028", prefix: "นาย", fname: "เกียรติยศ", lname: "จันทร์เพ็ง", nickname: "ขนมเข่ง", email: "66200028@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200033", prefix: "นาย", fname: "คมกฤษ", lname: "บินล่าเต๊ะ", nickname: "กฤษ", email: "66200033@kmitl.ac.th", phone: "0611769547", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200051", prefix: "นาย", fname: "ชนสรณ์", lname: "ทองน้ำวน", nickname: "", email: "66200051@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200052", prefix: "นาย", fname: "ชนะพงศ์พันธุ์", lname: "ทรัพย์มี", nickname: "พีท", email: "66200052@kmitl.ac.th", phone: "095963099", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200059", prefix: "นาย", fname: "ชิษณุพงศ์", lname: "งามน้อย", nickname: "นนท์", email: "66200059@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200062", prefix: "นาย", fname: "ฐิติกร", lname: "กี้ข้อ", nickname: "", email: "66200062@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200063", prefix: "นาย", fname: "ฑีฆทัศน์", lname: "คำระหง", nickname: "ที", email: "66200063@kmitl.ac.th", phone: "0959029373", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200082", prefix: "นาย", fname: "ดัสกร", lname: "ทับแสง", nickname: "โทมัส", email: "66200082@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200098", prefix: "นาย", fname: "ธนดล", lname: "ขวุนแขวง", nickname: "", email: "66200098@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200105", prefix: "นาย", fname: "ธนะวัฒน์", lname: "บุญประสพ", nickname: "ไนซ์", email: "66200105@kmitl.ac.th", phone: "0932491392", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200108", prefix: "นาย", fname: "ธนายุทธ", lname: "ศรีเรือง", nickname: "ปอนด์", email: "66200108@kmitl.ac.th", phone: "0834547706", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200113", prefix: "นาย", fname: "ธัญวุฒิ", lname: "ลีวังศรี", nickname: "", email: "66200113@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200117", prefix: "นาย", fname: "ธีรเดช", lname: "แสงอรุณ", nickname: "เอิร์ธ", email: "66200117@kmitl.ac.th", phone: "0620780682", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200122", prefix: "นาย", fname: "ธีรภัทร์", lname: "อามาตย์", nickname: "นิค", email: "66200122@kmitl.ac.th", phone: "0925603534", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200137", prefix: "นางสาว", fname: "บัณฑิตา", lname: "วงศ์อนุรักษ์กุล", nickname: "มุก", email: "66200137@kmitl.ac.th", phone: "0825091864", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200141", prefix: "นาย", fname: "ปฐมพงศ์", lname: "ปานเกลี้ยง", nickname: "ตังๆ", email: "66200141@kmitl.ac.th", phone: "0635806948", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200157", prefix: "นาย", fname: "ปัณณวิชญ์", lname: "ยงภูมิพุทธา", nickname: "", email: "66200157@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200160", prefix: "นาย", fname: "ปิยภัสร์", lname: "อัจฉราทิพย์", nickname: "", email: "66200160@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200166", prefix: "นาย", fname: "พงศ์พณิช", lname: "อินทร์เทพ", nickname: "เจมส์", email: "66200166@kmitl.ac.th", phone: "0614875561", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200174", prefix: "นาย", fname: "พรเทพ", lname: "สิงคะ", nickname: "", email: "66200174@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200179", prefix: "นางสาว", fname: "พลอยชมพู", lname: "เลิศพนนนท์", nickname: "พิมพลอย", email: "66200179@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200184", prefix: "นาย", fname: "พีรพัฒน์", lname: "สมพงษ์", nickname: "", email: "66200184@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200190", prefix: "นางสาว", fname: "เพ็ญพิชาา", lname: "กาญจนพานิชย์", nickname: "แพน", email: "66200190@kmitl.ac.th", phone: "0935814918", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200193", prefix: "นาย", fname: "ภควัต", lname: "พิชัยณรงค์", nickname: "", email: "66200193@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200238", prefix: "นาย", fname: "วรวิช", lname: "แซ่ซิ่น", nickname: "บอม", email: "66200238@kmitl.ac.th", phone: "0935702132", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200245", prefix: "นาย", fname: "วิชญะ", lname: "อัธยาศัย", nickname: "ฟลุ๊ค", email: "66200245@kmitl.ac.th", phone: "0937839678", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200248", prefix: "นาย", fname: "วีรภาพ", lname: "เจียรพันธ์", nickname: "ปอนด์", email: "66200248@kmitl.ac.th", phone: "0806458931", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200250", prefix: "นาย", fname: "ศตายุ", lname: "ใสสว่าง", nickname: "หมวด", email: "66200250@kmitl.ac.th", phone: "0622310206", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200257", prefix: "นาย", fname: "ศิรชัช", lname: "สุทธิรัตน์", nickname: "", email: "66200257@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200277", prefix: "นาย", fname: "สิฐวุฒิ", lname: "จิตต์สวัสดิ์", nickname: "", email: "66200277@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200301", prefix: "นาย", fname: "อติชาต", lname: "ทองเปลว", nickname: "ซันนี่", email: "66200301@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200316", prefix: "นาย", fname: "อำนาจ", lname: "งามเอก", nickname: "", email: "66200316@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200326", prefix: "นาย", fname: "กิตตินันท์", lname: "คูหา", nickname: "ซันนี่", email: "66200326@kmitl.ac.th", phone: "0989055242", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200328", prefix: "นาย", fname: "คำรณ", lname: "รักเชียง", nickname: "", email: "66200328@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200336", prefix: "นางสาว", fname: "ชฎาภรณ์", lname: "โพธิ์ศิริ", nickname: "เเก้ม", email: "66200336@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200338", prefix: "นาย", fname: "ชนัฐกร", lname: "อริยะอมรเลิศ", nickname: "พีวี", email: "66200338@kmitl.ac.th", phone: "0616288197", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200339", prefix: "นางสาว", fname: "ชนินาถ", lname: "ปิยะศาสตร์", nickname: "บัว", email: "66200339@kmitl.ac.th", phone: "0957218639", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200340", prefix: "นางสาว", fname: "ชมพูนุท", lname: "ศิริบุตร", nickname: "ชมปริ", email: "66200340@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200341", prefix: "นาย", fname: "ชยธร", lname: "แร่ทอง", nickname: "", email: "66200341@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200345", prefix: "นาย", fname: "ณฐกร", lname: "นิ่มกาญจนา", nickname: "", email: "66200345@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200347", prefix: "นางสาว", fname: "ณัชชา", lname: "ภูมิภัทรภักดี", nickname: "พิมรี่พาย", email: "66200347@kmitl.ac.th", phone: "0987427944", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200354", prefix: "นาย", fname: "ดรณ์", lname: "จรรยาเสน", nickname: "", email: "66200354@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200357", prefix: "นาย", fname: "ทินบดี", lname: "สุมังคละสมบัติ", nickname: "โอม", email: "66200357@kmitl.ac.th", phone: "0615605305", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200361", prefix: "นาย", fname: "ธีรนันท์", lname: "จันทร์กระจ่าง", nickname: "ดามมี่", email: "66200361@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200383", prefix: "นาย", fname: "ภัทรดนัย", lname: "บุญไทย", nickname: "พีท", email: "66200383@kmitl.ac.th", phone: "0991327031", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200389", prefix: "นางสาว", fname: "วนัชพร", lname: "ฉายบุญครอง", nickname: "ใบตอง", email: "66200389@kmitl.ac.th", phone: "0944735671", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200395", prefix: "นางสาว", fname: "วาสิตาใจรังษี", lname: "", nickname: "ปอฝ้าย", email: "66200395@kmitl.ac.th", phone: "0622192487", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200396", prefix: "นางสาว", fname: "วิชญาพร", lname: "ยาจิ๋ว", nickname: "เกียว", email: "66200396@kmitl.ac.th", phone: "0855053636", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200407", prefix: "นาย", fname: "สรกฤต", lname: "มีอินทร์", nickname: "", email: "66200407@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200408", prefix: "นาย", fname: "สหเกียรติ์", lname: "กาญจนรัตน์", nickname: "ตี๋", email: "66200408@kmitl.ac.th", phone: "0618585405", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200411", prefix: "นาย", fname: "สิรภพ", lname: "ปิติชูชีพ", nickname: "เบสท์", email: "66200411@kmitl.ac.th", phone: "0953176495", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200415", prefix: "นาย", fname: "สุรชาติ", lname: "คงสงค์", nickname: "บอล", email: "66200415@kmitl.ac.th", phone: "0980807909", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200420", prefix: "นาย", fname: "อภิศักดิ์", lname: "เพชรเศษ", nickname: "โย", email: "66200420@kmitl.ac.th", phone: "0937154851", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200423", prefix: "นาย", fname: "อัครวินท์", lname: "ดัชนี", nickname: "", email: "66200423@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "66200425", prefix: "นาย", fname: "จิราเดช", lname: "พยุหกฤษ", nickname: "ต้า", email: "66200425@kmitl.ac.th", phone: "", gen: "CE03", majorId: "CE", roleId: "student" },
      { StudentId: "67200014", prefix: "นางสาว", fname: "กัณฐมณี", lname: "กอบการ", nickname: "หงส์ทอง", email: "67200014@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200024", prefix: "นาย", fname: "กิตติศักดิ์", lname: "รัตนรักษ์", nickname: "ฟิว", email: "67200024@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200030", prefix: "นาย", fname: "คณพัฒน์", lname: "รุ่งรพีพรพงษ์", nickname: "จอร์จ", email: "67200030@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200031", prefix: "นาย", fname: "คณาธิป", lname: "วิเชียรศรี", nickname: "เจ้านาย", email: "67200031@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200032", prefix: "นาย", fname: "คมสัน", lname: "หัสบงกต", nickname: "เค", email: "67200032@kmitl.ac.th", phone: "0930878882", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200049", prefix: "นาย", fname: "เจษฎา", lname: "ศรีสง่า", nickname: "พี", email: "67200049@kmitl.ac.th", phone: "0626253837", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200050", prefix: "นาย", fname: "เฉลิมรัฐ", lname: "เพ็ชรสุวรรณ", nickname: "เบนซ์", email: "67200050@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200062", prefix: "นางสาว", fname: "ชุติกาญจน์", lname: "แก้วสมศรี", nickname: "ไอซ์", email: "67200062@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200071", prefix: "นาย", fname: "ณภัทร", lname: "ตุลารักษ์", nickname: "ออฟ", email: "67200071@kmitl.ac.th", phone: "0945467644", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200079", prefix: "นางสาว", fname: "ณัฐธิดา", lname: "เกื้อประจง", nickname: "อัน", email: "67200079@kmitl.ac.th", phone: "0801585306", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200081", prefix: "นาย", fname: "ณัฐนนท์", lname: "ชุมบุญ", nickname: "นนท์", email: "67200081@kmitl.ac.th", phone: "0968712489", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200088", prefix: "นาย", fname: "ณิพิชญ์", lname: "มาศเมฆ", nickname: "เอี๊ยก", email: "67200088@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200093", prefix: "นาย", fname: "นายตระกูลชัย", lname: "เเซ่ติ้ง", nickname: "เฮ้าซุง", email: "67200093@kmitl.ac.th", phone: "0980850838", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200099", prefix: "นาย", fname: "ทัชภูมิ", lname: "ใจดี", nickname: "ไปน์", email: "67200099@kmitl.ac.th", phone: "0986782950", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200102", prefix: "นาย", fname: "ทีปกิติ์", lname: "พรหมสัตยพรต", nickname: "ริว", email: "67200102@kmitl.ac.th", phone: "0973016465", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200103", prefix: "นาย", fname: "ทีปศ์ยุส", lname: "พิจยานนท์", nickname: "น้ำแร่", email: "67200103@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200107", prefix: "นาย", fname: "ธนโชติ", lname: "เพ็ชรรัตน์", nickname: "อ๋า", email: "67200107@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200119", prefix: "นาย", fname: "ธฤต", lname: "อ่องมะลิ", nickname: "วิน", email: "67200119@kmitl.ac.th", phone: "0970360046", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200127", prefix: "นาย", fname: "ธีเดช", lname: "สถิรสมบัติ", nickname: "ติณณ์", email: "67200127@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200134", prefix: "นาย", fname: "นภดล", lname: "ขาวดี", nickname: "ปอร์ซ่า", email: "67200134@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200148", prefix: "นาย", fname: "เนติภูมิ", lname: "มีศรี", nickname: "ไอเซน โซสุเกะ", email: "67200148@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200155", prefix: "นาย", fname: "ปฏิภาณ", lname: "เสนาป่า", nickname: "ปาล์ม", email: "67200155@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200165", prefix: "นางสาว", fname: "ปัณณพร", lname: "พรหมรักษ์", nickname: "โบนัส", email: "67200165@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200172", prefix: "นางสาว", fname: "ปิ่นปินัทธ์", lname: "เข็มทอง", nickname: "ปิ่น", email: "67200172@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200219", prefix: "นาย", fname: "ภูวดล", lname: "วิสาละ", nickname: "เดล", email: "67200219@kmitl.ac.th", phone: "0611301594", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200223", prefix: "นาย", fname: "นายมีสุข", lname: "เอกพงษ์", nickname: "โก้", email: "67200223@kmitl.ac.th", phone: "0935654015", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200235", prefix: "นางสาว", fname: "รินรดา", lname: "บุญมี", nickname: "เนนย", email: "67200235@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200258", prefix: "นาย", fname: "วุฒิชัย", lname: "อ่องรัตนากุล", nickname: "เฟิร์ส", email: "67200258@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200272", prefix: "นาย", fname: "ศุภฤกษ์", lname: "มะนะกุล", nickname: "ฟิวส์", email: "67200272@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200277", prefix: "นาย", fname: "สรวิศ", lname: "บัวขนาบ", nickname: "ปันนี่", email: "67200277@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200305", prefix: "นาย", fname: "อนิวัต", lname: "ยะคำ", nickname: "ภู", email: "67200305@kmitl.ac.th", phone: "0987294984", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200324", prefix: "นาย", fname: "กนกพัฒน์", lname: "โพธิ", nickname: "ปลาหมอ", email: "67200324@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200344", prefix: "นาย", fname: "ชวัลวิทย์", lname: "จันทร์ศุกฤกษ์", nickname: "ปังปอนด์", email: "67200344@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200348", prefix: "นาย", fname: "ณรงค์รักษ์", lname: "เรืองศักดิ์", nickname: "ไอซ์", email: "67200348@kmitl.ac.th", phone: "0929744516", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200349", prefix: "นาย", fname: "ณัควัต", lname: "เศรษฐเอกพันธ์", nickname: "สำเนา", email: "67200349@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200350", prefix: "นางสาว", fname: "ณัฏฐ์ชยา", lname: "จำปา", nickname: "วาวา", email: "67200350@kmitl.ac.th", phone: "0650053473", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200351", prefix: "นาย", fname: "ณัฐธนน", lname: "ทุมรัตน์", nickname: "ตั้น", email: "67200351@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200357", prefix: "นาย", fname: "ดนุพล", lname: "จิ้วพงศสวัสดิ์", nickname: "นิว", email: "67200357@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200367", prefix: "นางสาว", fname: "ธัญญรัตน์", lname: "ส่งสมใจ", nickname: "โมริ", email: "67200367@kmitl.ac.th", phone: "0964159745", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200368", prefix: "นาย", fname: "ธีรภัทร", lname: "ทองสิงห์", nickname: "เจมส์", email: "67200368@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200369", prefix: "นาย", fname: "นายธีรศาสนต์", lname: "คงเกิด", nickname: "Tee", email: "67200369@kmitl.ac.th", phone: "0656709042", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200375", prefix: "นาย", fname: "ปฏิภาณ", lname: "ประพฤติดี", nickname: "ไบร์ท", email: "67200375@kmitl.ac.th", phone: "0941240631", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200380", prefix: "นาย", fname: "ปรินทร", lname: "คงทอง", nickname: "แบงค์", email: "67200380@kmitl.ac.th", phone: "0631102883", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200381", prefix: "นาย", fname: "ปารเมศ", lname: "สิงคะ", nickname: "มอสซี่", email: "67200381@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200401", prefix: "นาย", fname: "ภุมเรศ", lname: "หมื่นระย้า", nickname: "ฟา", email: "67200401@kmitl.ac.th", phone: "0619161928", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200412", prefix: "นาย", fname: "รุจิณัฐ", lname: "อาศิรเมธี", nickname: "ฟ้า", email: "67200412@kmitl.ac.th", phone: "0800479886", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200419", prefix: "นางสาว", fname: "วิมลสิริ", lname: "บุญยก", nickname: "พิงค์", email: "67200419@kmitl.ac.th", phone: "0971264731", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200439", prefix: "นาย", fname: "สุทธิธนินท์", lname: "อัครมณีนันท์", nickname: "โชกุน", email: "67200439@kmitl.ac.th", phone: "0826420942", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200452", prefix: "นาย", fname: "อัษฎายุธ", lname: "พันธ์รักษ์ณรงค์", nickname: "ฟีฟ่า", email: "67200452@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200460", prefix: "นาย", fname: "สุรเดช", lname: "กรณ์ศิริ", nickname: "ไอซ์", email: "67200460@kmitl.ac.th", phone: "", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200010", prefix: "นาย", fname: "กฤษณะ", lname: "สุขกรี", nickname: "ฟิล์ม", email: "67200010@kmitl.ac.th", phone: "0936268091", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200400", prefix: "นาย", fname: "ภิญญู", lname: "ณัฐญาติมา", nickname: "บอมบ์", email: "67200400@kmitl.ac.th", phone: "0957795165", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200063", prefix: "นางสาว", fname: "ชุติกาญจน์", lname: "แซ่อึ้ง", nickname: "ตา", email: "67200063@kmitl.ac.th", phone: "0823456141", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "67200023", prefix: "นาย", fname: "กิตติพัฒน์", lname: "ผกามาศ", nickname: "ไทเกอร์", email: "67200023@kmitl.ac.th", phone: "0630626891", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "65200123", prefix: "นาย", fname: "ณัฐวัฒน์", lname: "อาทรกิจวัฒน์", nickname: "ฟิง", email: "65200123@kmitl.ac.th", phone: "0941493541", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "67200187", prefix: "นาย", fname: "พศุตม์", lname: "เพชรรอด", nickname: "ออฟ", email: "67200187@kmitl.ac.th", phone: "0930611106", gen: "CE04", majorId: "CE", roleId: "student" },
      { StudentId: "65200276", prefix: "นาย", fname: "ภูสิทธิ์", lname: "หล้าเพชร", nickname: "ภูมิ", email: "65200276@kmitl.ac.th", phone: "", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "65200237", prefix: "นาย", fname: "พิชญุตม์", lname: "อุ่นนวล", nickname: "ภูมิ", email: "65200237@kmitl.ac.th", phone: "0619872063", gen: "CE02", majorId: "CE", roleId: "student" },
      { StudentId: "68200051", prefix: "นางสาว", fname: "ขนิษฐา", lname: "พัฒน์งามกุล", nickname: "", email: "68200051@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200059", prefix: "นาย", fname: "กษาปณ์", lname: "จงศักดิ์", nickname: "", email: "68200059@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200097", prefix: "นางสาว", fname: "ชญา", lname: "ขจรเจริญ", nickname: "", email: "68200097@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200131", prefix: "นางสาว", fname: "ณัฐณิชา", lname: "ช่วยศรีนาค", nickname: "", email: "68200131@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200134", prefix: "นาย", fname: "ณัฐดนัย", lname: "พันธุ์ธัญญะ", nickname: "", email: "68200134@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200136", prefix: "นาย", fname: "ณัฐวรรธน์", lname: "ธาราทอง", nickname: "", email: "68200136@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200177", prefix: "นาย", fname: "ณัฐพล", lname: "แป้นเมือง", nickname: "", email: "68200177@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200193", prefix: "นาย", fname: "ณัฐพล", lname: "โพธิ์ภู่", nickname: "", email: "68200193@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200204", prefix: "นาย", fname: "ณัฐพล", lname: "วงษ์ศรีนวล", nickname: "", email: "68200204@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200213", prefix: "นาย", fname: "ณัฐวัฒน์", lname: "ปลอดกลาง", nickname: "", email: "68200213@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200214", prefix: "นาย", fname: "ณัฐวัฒน์", lname: "ลีรัตนขจร", nickname: "", email: "68200214@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200221", prefix: "นาย", fname: "ณัฐพล", lname: "ศรีเพ็ญ", nickname: "", email: "68200221@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200224", prefix: "นาย", fname: "ณัฐพล", lname: "เทียนทอง", nickname: "", email: "68200224@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200232", prefix: "นาย", fname: "ณัฐกิตติ", lname: "ตระหง่าน", nickname: "", email: "68200232@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200243", prefix: "นาย", fname: "ปรัชกร", lname: "สมบูรณ์", nickname: "", email: "68200243@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200244", prefix: "นาย", fname: "ปรินันท์", lname: "พิริยานันท์", nickname: "", email: "68200244@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200256", prefix: "นางสาว", fname: "ปัญจพัฒน์", lname: "ศุภดาคร", nickname: "", email: "68200256@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200259", prefix: "นาย", fname: "ปณณัฐ", lname: "กุ้งเรือง", nickname: "", email: "68200259@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200261", prefix: "นาย", fname: "ปณิธาน", lname: "วรรณาคม", nickname: "", email: "68200261@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200265", prefix: "นาย", fname: "ปานพงษ์", lname: "จุ้ยลา", nickname: "", email: "68200265@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200268", prefix: "นางสาว", fname: "ปาลิตา", lname: "ไทยกรสุมพงษา", nickname: "", email: "68200268@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200269", prefix: "นาย", fname: "ปัญจพล", lname: "วรรณาคม", nickname: "", email: "68200269@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200307", prefix: "นาย", fname: "ศุภศักดิ์", lname: "จิตนพรัตน์ทรงศ์", nickname: "", email: "68200307@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200310", prefix: "นาย", fname: "พรชัย", lname: "ไก่กามา", nickname: "", email: "68200310@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200328", prefix: "นาย", fname: "ภูมินัฐ", lname: "บุญทอง", nickname: "", email: "68200328@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200352", prefix: "นาย", fname: "ชาญณรงค์", lname: "พรหมพิสิฐย์", nickname: "", email: "68200352@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200362", prefix: "นาย", fname: "ศราวุฒิ", lname: "เทียนวิเศษ", nickname: "", email: "68200362@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200367", prefix: "นาย", fname: "ฐิติภูมิ", lname: "สุวรรณเสนีย์", nickname: "", email: "68200367@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200379", prefix: "นาย", fname: "ชัชพิสิษฐ์", lname: "บุญปลอดมณี", nickname: "", email: "68200379@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200399", prefix: "นาย", fname: "ชินวัตร", lname: "ทนิลผล", nickname: "", email: "68200399@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200402", prefix: "นางสาว", fname: "ภาวิชญ์", lname: "คำมาศ", nickname: "", email: "68200402@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200420", prefix: "นาย", fname: "คิษฎ์ฑิธิ์", lname: "ทองาวา", nickname: "", email: "68200420@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200422", prefix: "นางสาว", fname: "จุฑามาศ", lname: "สุวรรณน้อย", nickname: "", email: "68200422@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200424", prefix: "นาย", fname: "สิรวิชญ์", lname: "จำปา", nickname: "", email: "68200424@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200451", prefix: "นาย", fname: "อัครเดช", lname: "ยะสุพงษ์", nickname: "", email: "68200451@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200452", prefix: "นาย", fname: "ณัฐวุฒิ", lname: "บุตรบุญ", nickname: "", email: "68200452@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200453", prefix: "นาย", fname: "ณัฐพล", lname: "สุทธิศิริกุล", nickname: "", email: "68200453@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200534", prefix: "นาย", fname: "พีรพงศ์", lname: "เกียรติการุณ", nickname: "", email: "68200534@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200558", prefix: "นาย", fname: "กฤษฎา", lname: "หุมสงค์", nickname: "", email: "68200558@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200574", prefix: "นาย", fname: "ณัฐนันท์", lname: "สิงหรอบทนต์", nickname: "", email: "68200574@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200580", prefix: "นาย", fname: "ณัฐนนท์", lname: "เหมือนมณี", nickname: "", email: "68200580@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200591", prefix: "นาย", fname: "พศิน", lname: "สมมุติ", nickname: "", email: "68200591@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200596", prefix: "นาย", fname: "ปรเมษฐ์", lname: "ศรัทธาดี", nickname: "", email: "68200596@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200613", prefix: "นาย", fname: "เทวินทร์", lname: "เกตุสุวรรณ", nickname: "", email: "68200613@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200634", prefix: "นาย", fname: "ณณากานต์", lname: "ฤทธิไกร", nickname: "", email: "68200634@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200640", prefix: "นาย", fname: "ยุทธศรี", lname: "อินทร์เอี่ยม", nickname: "", email: "68200640@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200670", prefix: "นาย", fname: "ธิวาวุฒิ", lname: "ช่วยชูกลิ่น", nickname: "", email: "68200670@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200687", prefix: "นาย", fname: "ธิติภัทร", lname: "หัตถา", nickname: "", email: "68200687@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" },
      { StudentId: "68200691", prefix: "นาย", fname: "ธิติศรพงษ์", lname: "อวยพร", nickname: "", email: "68200691@kmitl.ac.th", phone: "", gen: "CE05", majorId: "CE", roleId: "student" }
    ],
    skipDuplicates: true
  });

  // ---------- TEACHERS ----------
  // (เพิ่มส่วนนี้ให้เป็น option ในกรณีที่คุณใช้ Table User สำหรับอาจารย์ด้วย)
  await prisma.user.createMany({
    data: [
      { StudentId: "", prefix: "อาจารย์", fname: "อรรถศาสตร์", lname: "นาตเทวัญ", nickname: "อ๊อด", email: "athasart.na@kmitl.ac.th", phone: "0816326779", gen: "", majorId: "CE", roleId: "teacher" },
      { StudentId: "", prefix: "นาย", fname: "จตุรงค์", lname: "เกตุนิมิต", nickname: "โอม", email: "jaturong.ka@kmitl.ac.th", phone: "", gen: "", majorId: "CE", roleId: "teacher" },
      { StudentId: "", prefix: "อาจารย์", fname: "นภัทรพี", lname: "สิทธิวัจน", nickname: "แฮปปี้", email: "pisakorn.si@kmitl.ac.th", phone: "", gen: "", majorId: "CE", roleId: "teacher" },
      { StudentId: "", prefix: "อาจารย์", fname: "รัตติกร", lname: "สมบัติเเก้ว", nickname: "จุ๋ม", email: "rattikorn.so@kmitl.ac.th", phone: "0877110520", gen: "", majorId: "CE", roleId: "teacher" },
      { StudentId: "", prefix: "ว่าที่ ร.ต.", fname: "ศิลา", lname: "ศิริมาสกุล", nickname: "ติ๊ก", email: "silar.si@kmitl.ac.th", phone: "", gen: "", majorId: "CE", roleId: "teacher" }
    ],
    skipDuplicates: true
  });


  console.log("Users seeded successfully")

}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
